version: '3.1'
services:
  app:
    container_name: spring-docker-kubernetes
    image: spring-docker-kubernetes
    build: ./
    ports:
    - "7777:7777"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
    - "5431:5431"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbdockerdev